# Generated by Django 5.2.1 on 2025-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="level",
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.CharField(default="Allgemein", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(default="Beschreibung folgt"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="icon",
            field=models.CharField(default="fa-code", max_length=50),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
