# Generated by Django 5.2.1 on 2025-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0002_remove_skill_level_skill_category_skill_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
