# Generated by Django 5.2.1 on 2025-05-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_project_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="project_pdfs/"),
        ),
        migrations.AddField(
            model_name="project",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="project_videos/"),
        ),
    ]
