# Generated by Django 5.2.1 on 2025-05-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="blog_pdfs/"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="blog_videos/"),
        ),
    ]
