# Generated by Django 5.2.1 on 2025-05-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_blogpost_image_blogpost_pdf_blogpost_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
