# Generated by Django 5.2.1 on 2025-05-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_contactinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="social_media",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="transfermarkt",
            field=models.URLField(blank=True),
        ),
    ]
