# Generated by Django 5.2.1 on 2025-05-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_alter_project_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="link",
        ),
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True, verbose_name="GitHub Link"),
        ),
    ]
